spring:
  application:
    name: TPO_04
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:mem:books
    username: misalitvin
    password: BBNB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql/publisher.sql,classpath:sql/author.sql,classpath:sql/book.sql,classpath:sql/book_author.sql